In [2]:
## From getting started in scikit-learn with the famous iris dataset, (Data school)
# Import load_iris function from datasets module
from sklearn.datasets import load_iris

In [3]:
# Save bunch object containing iris dataset and its attributes
iris = load_iris()

# Type is Bunch
type(iris)

# Print the data 150x4 matrix which will becomne training data set
# the rows are also called obesrvations and the columns are also called features.
print (iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [4]:
# Print the name of the 4 features, (columns)
print (iris.feature_names)

# Print the integers representing the species of each observation
print (iris.target)

# Print the encoding scheme for species: 0 = sertosa, 1 = versacolor, 2 = virginica
print(iris.target_names)


['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [5]:
# Check the types of the features and response
print (type(iris.data))
print (type(iris.target))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
# Check the shape of the features (first dimention = the number of observations, second dimention = number of features)
print(iris.data.shape)

# Check the shape of the response (single dimension matching the number of observations from data.shape)
print(iris.target.shape)

(150, 4)
(150,)


In [7]:
# Store feature matrix in X
X=iris.data

# Store response vector in y
y=iris.target

Training a machine learning model with scikit-learn
From the Data School video series:Introduction to machine learning with scikit-learn 

Now that we're familiar with the famous iris dataset, let's actually use a classification model in scikit-learn to predict the species of an iris! 

We'll learn how the K-nearest neighbors (KNN) model works

Then walk through the four steps for model training and prediction in scikit-learn. 

Finally, we'll see how easy it is to try out a different classification model, namely logistic regression.

Scikit-learn 4 step modeling pattern to follow:   

In [8]:
# 1: Import the class to use 
from sklearn.neighbors import KNeighborsClassifier

In [9]:
# 2: Instantiate the estimator with tuning parameter
knn = KNeighborsClassifier(n_neighbors=1)

In [10]:
print (knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=1, p=2,
           weights='uniform')


In [11]:
# 3: Fit the model with data
knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=1, p=2,
           weights='uniform')

In [12]:
# Predict the response for a new observation
knn.predict([[3, 5, 4, 2]])
# Returns the predicted response value, (Virginica)

array([2])

In [13]:
# Predict the response for multiple observations
x_new = [[3, 5, 4, 2], [5, 4, 3, 2]]
knn.predict(x_new)

array([2, 1])

Model tuning example: K=5

In [14]:
# 2: Instantiate the estimator with tuning parameter
knn = KNeighborsClassifier(n_neighbors=5)

# 3: Fit the model with data
knn.fit(X, y)

# Predict the response for a new observation
knn.predict(x_new)
# Returns the predicted response value, (versacolor)

array([1, 1])

Use a different classification model

In [17]:
# 1: Import the class to use 
from sklearn.linear_model import LogisticRegression

# 2: Instantiate the estimator with tuning parameter to get past the extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
logreg = LogisticRegression(max_iter = 4000, solver='lbfgs', multi_class='auto')

# 3: Fit the model with data
logreg.fit(X, y)

# Predict the response for a new observation
x_new = [[3, 5, 4, 2], [5, 4, 3, 2]]
logreg.predict(x_new)

# Store the predicted response values
y_pred = logreg.predict(X)

Comparing machine learning models in scikit-learn

Classification accuracy
Proporion of correct predictions
Evaluation metric for classification problems

In [18]:
# Compute classification accuracy for logistic regression model
from sklearn import metrics
print(metrics.accuracy_score(y, y_pred))

0.9733333333333334


In [19]:
# Compute classification accuracy for KNN (K=5) model
# 2: Instantiate the estimator with tuning parameter
knn = KNeighborsClassifier(n_neighbors=5)

# 3: Fit the model with data
knn.fit(X, y)

# Predict the response for the data
knn.predict(X)

# Store the predicted response values
y_pred = knn.predict(X)
print(metrics.accuracy_score(y, y_pred))

0.9666666666666667


In [21]:
# Compute classification accuracy for KNN (K=1) model
# 2: Instantiate the estimator with tuning parameter
knn = KNeighborsClassifier(n_neighbors=1)

# 3: Fit the model with data
knn.fit(X, y)

# Predict the response for the data
knn.predict(X)

# Store the predicted response values
y_pred = knn.predict(X)
print(metrics.accuracy_score(y, y_pred))

# A value of 1.0 should be expected as it is the training data
# Training and testing your data on the same model is not a wise choise
# Low tuning parameters tend to produce poor predictions in out of sample data.

1.0


The preferred method for evaluation is train/test split where 40-60% of the data is used to train while the remainder is used to test:

Split the dataset into a training set and a testing set.
Train the model on trainig data
Test the model on testing data
Evaluate to see how we did

In [22]:
# What are the shapes of the data
print (X.shape)
print(y.shape)

(150, 4)
(150,)


In [ ]:
# Step 1: Split X and y into training and test sets